source 'https://github.com/CocoaPods/Specs.git'

target 'MRGDateFormatter_Example', :exclusive => true do
  pod "MRGDateFormatter", :path => "../"
end

target 'MRGDateFormatter_Tests', :exclusive => true do
  pod "MRGDateFormatter", :path => "../"

  
end
